Book/config/routes.rb
Rails.application.routes.draw do 
  devise_for :users, controllers: {
    registrations: "users/registrations",
    sessions: "users/sessions"
}
namespace :api do
    namespace :v1 do 
      resources :books
      devise_for :users, controllers: {
        sessions: "api/v1/sessions",
        registrations: "api/v1/registrations"
      }

      resources :books, only: [ :index, :show, :create, :update, :destroy ]
    end
  end
  root "books#index"
  resources :books do
  resources :reviews, only: [ :create, :edit, :update, :destroy ]
  end
end

Book/app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :authenticate_user!
  # load_and_authorize_resource
  def create
   @book = Book.find(params[:book_id])
  @review = @book.reviews.build(review_params) # Use .build to instantiate the review
  @review.user= current_user
    if @review.save
      redirect_to @book, notice: "Review was successfully created."
    else
      redirect_to @book, alert: "Unable to create review."
    end
  end
  def update
     @book = Book.find(params[:book_id])
    @review = @book.reviews.find(params[:id])
    if can?(:update, @review)
      if @review.update(review_params)
        redirect_to @review.book, notice: "Review was successfully updated."
      else
        render :edit
      end
    else
      redirect_to @review.book, notice: "Access denied: You don't have permission to update this review."
    end
  end

  def destroy
     @book = Book.find(params[:book_id])
    @review = @book.reviews.find(params[:id])

    if can?(:destroy, @review)
      @review.destroy
      # redirect_to @review.book, notice: "Review was successfully destroyed."
    else
      redirect_to books_url, notice: "Access denied: You don't have permission to destroy this review."
    end
  end
    def edit
      @book = Book.find(params[:book_id])
      @review = Review.find(params[:id])
    end

    private
    def review_params
      params.require(:review).permit(:reviewer, :msg)
    end
end

Book/app/helpers/reviews_helper.rb
module ReviewsHelper
end

Book/app/views/reviews/_form.html.erb
<%= form_with model: [book, book.reviews.build] do |form| %>
  <p>
    <%= form.label :User %><br>
    <%= form.text_field :reviewer %>
  </p>
  <p>
    <%= form.label :Review %><br>
    <%= form.text_area :msg %>
  </p>
  <p>
    <%= form.submit %>
  </p>
<% end %>

Book/app/views/reviews/_review.html.erb
<p>
  <h4>User:</h4>
<%= review.reviewer %>
</p>

<p>
  <h4>Review:</h4>
  <%= review.msg %>
</p>
<%= link_to "Update it", edit_book_review_path(@book, review) %>

<h5><%= link_to "Destroy", [@book, review], data: {
                                              turbo_method: :delete,
                                              turbo_confirm: "Are you sure?",
                                            } %></h5>

Book/app/views/reviews/edit.html.erb
<h2>Edit Review</h2>
<%= form_with model: [@book, @review] do |form| %>
  <p>
    <%= form.label :reviewer %><br>
    <%= form.text_field :reviewer %>
  </p>

  <p>
    <%= form.label :msg, "Message" %><br>
    <%= form.text_area :msg %>
  </p>

  <p>
    <%= form.submit "Update Review" %>
  </p>
<% end %>

<%= link_to "Back", book_path(@book) %>