Book/config/routes.rb
Rails.application.routes.draw do 
  devise_for :users, controllers: {
    registrations: "users/registrations",
    sessions: "users/sessions"
}
namespace :api do
    namespace :v1 do 
      resources :books
      devise_for :users, controllers: {
        sessions: "api/v1/sessions",
        registrations: "api/v1/registrations"
      }

      resources :books, only: [ :index, :show, :create, :update, :destroy ]
    end
  end
  root "books#index"
  resources :books do
  resources :reviews, only: [ :create, :edit, :update, :destroy ]
  end
end

Book/app/models/book.rb
class Book < ApplicationRecord
  has_many :reviews, dependent: :destroy
  validates :title, presence: true
  validates :author_name, presence: true
  # validates :description, presence:true
  belongs_to :user
end

Book/app/controllers/api/v1/books_controller.rb
class Api::V1::BooksController < ApplicationController

  skip_before_action :verify_authenticity_token, only: [ :create, :update, :destroy ]
  # before_action :authorize_post, only: [ :edit, :update, :destroy ]
  # before_action :authenticate_user!, unless: -> { Rails.env.test? }
  before_action :set_book, only: [ :show, :update, :destroy ]

  def index
    @books = current_user.books
    render json: @books
  end

  def show
    render json: @book
  end

  def create
    @book = current_user.books.build(book_params)
    if @book.save
      render json: @book, status: :created
    else
      render json: @book.errors, status: :unprocessable_entity
    end
  end

  def update
    if @book.update(book_params)
      render json: @book, status: :ok
    else
      render json: @book.errors, status: :unprocessable_entity
    end
  end

  def destroy
    @book.destroy
    head :no_content
  end

  private

  def set_book
    @book = current_user.books.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    render json: { error: 'Book not found' }, status: :not_found
  end

  def book_params
    params.require(:book).permit(:title, :author_name, :description, :published_date)
  end
end

Book/app/controllers/books_controller.rb
class BooksController < ApplicationController
  # http_basic_authenticate_with name: "dani", password: "secret", except: [ :index, :show ]
  # before_action :authenticate_user!
  # before_action :require_admin, only: [ :destroy ]
  # load_and_authorize_resource

  include Pagy::Backend
  def index
    if params[:query].present?
      @pagy, @books = pagy(Book.search_books(params[:query]))
    else
      @pagy, @books = pagy(Book.all)
    end
  end

  def show
    @book = Book.find(params[:id])
  end

  def new
    @book = Book.new
  end

  def create
    @book = current_user.books.build(book_params)  # Associates the book with the current user
    if @book.save
      redirect_to @book, notice: "Book was successfully created."
    else
      render :new
    end
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    if can?(:update, @book)
    if @book.update(book_params)
      redirect_to @book, notice: "Book was successfully updated."
    else
      render :edit
    end
    else
    redirect_to book_path, notice: "Access denied: You don't have permission to update this post."
    end
  end

  def destroy
    @book = Book.find(params[:id])
    if can?(:destroy, @book)
    @book.destroy
    redirect_to books_url, notice: "Book was successfully destroyed."
    else
        redirect_to books_url, notice: "Access denied: You don't have permission to destroy this post."
    end
  end

  private

  # def require_admin
  #   unless current_user.admin?
  #     flash[:alert] = "Only admins can perform that action."
  #     redirect_to books_path
  #   end
  # end
  def find_book
    @book=Book.find(params[:id])
  end
  def book_params
    params.require(:book).permit(:title, :author_name, :description)
  end
end

Book/app/helpers/api/v1/books_helper.rb
module Api::V1::BooksHelper
end

Book/app/helpers/books_helper.rb
module BooksHelper
end

Book/app/views/books/_form.html.erb
<%= form_with model: book do |form| %>
  <div>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
    <% @book.errors.full_messages_for(:title).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

<div>
    <%= form.label :author_Name %><br>
    <%= form.text_field :author_name %>
    <% @book.errors.full_messages_for(:author_name).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :Description %><br>
    <%= form.text_area :description %><br>
    <% @book.errors.full_messages_for(:description).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.submit "Save" %>
  </div>
<% end %>

Book/app/views/books/edit.html.erb
<h1>Edit this book Details</h1>

<%= render "form", book: @book %>

Book/app/views/books/index.html.erb
<% if user_signed_in? %>
<h1>Books List</h1>
<table>
    <tr>
    <th>Book Title</th>
    <th>Author_Name</th>
    <th>Description</th>
    </tr>
    <% @books.each do |book| %>
    <tr>
        <td><%= link_to book.title, book %> </td>
        <td><%= book.author_name %></td>
        <td><%= book.description %> </td>
    </tr>
      <% end %>
</table>
<div class="pag-bar mt-5 pt-5 d-flex justify-content-center">
  <%== pagy_bootstrap_nav(@pagy) %>
</div>
<p><%= link_to "New Book", new_book_path %></p>
<% end %>

Book/app/views/books/new.html.erb
<h1>Add new Book</h1>

<%= render "form", book:@book %>

Book/app/views/books/show.html.erb
<h1><%= @book.title %></h1>
<h4><%= @book.author_name %></h4>
<p><%= @book.description %></p>

<%= link_to "Update it", edit_book_path(@book) %>
<h5><%= link_to "Destroy", book_path(@book), data: {
                                               turbo_method: :delete,
                                               turbo_confirm: "Are you sure?",
                                             } %></h5>

<h2>Reviews<h2>
<%= render @book.reviews %>
<h2>Add a Review:</h2>
<%= render "reviews/form", book: @book %>
<%= link_to "Back", books_url%>